spring.application.name=carChase
spring.datasource.url=jdbc:mysql://mysql-webpunkadmin.alwaysdata.net:3306/webpunkadmin_carchase?useSSL=true&serverTimezone=UTC
spring.datasource.username=386929
spring.datasource.password=superAdmin321123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect